# See: https://cwiki.apache.org/confluence/display/INFRA/git+-+.asf.yaml+features
github:
  features:
    # Enable issue management
    issues: true

notifications:
  commits: commits@royale.apache.org
  issues: dev@royale.apache.org
  pullrequests: dev@royale.apache.org
  
pelican:
  notify: dev@royale.apache.org
  # autobuild: preview/*
  theme: theme/apache
  whoami: main
  target: asf-site
